CREATE DATABASE IF NOT EXISTS resume_ai CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE resume_ai;

CREATE TABLE user (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(180) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(20) DEFAULT 'user',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resume (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 filename VARCHAR(255) NOT NULL,
 extracted_text LONGTEXT,
 resume_score FLOAT DEFAULT 0,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE job (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(180) NOT NULL,
 company VARCHAR(180) NOT NULL,
 location VARCHAR(180) DEFAULT 'Remote',
 description LONGTEXT NOT NULL,
 required_skills TEXT,
 min_experience FLOAT DEFAULT 0,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE match (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 resume_id INT NOT NULL,
 job_id INT NOT NULL,
 similarity_score FLOAT DEFAULT 0,
 skill_score FLOAT DEFAULT 0,
 final_score FLOAT DEFAULT 0,
 missing_skills TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE,
 FOREIGN KEY(resume_id) REFERENCES resume(id) ON DELETE CASCADE,
 FOREIGN KEY(job_id) REFERENCES job(id) ON DELETE CASCADE
);
